### ISSUE TITLE
BlastHTTP-1.2.1 build failure with http-conduit-2.3

### ISSUE THREAD

**Issue by DanBurton** [eggzilla/BlastHTTP#1]
As seen on the Stackage build server:

```
Building library for BlastHTTP-1.2.1..
[1 of 1] Compiling Bio.BlastHTTP    ( src/Bio/BlastHTTP.hs, dist/build/Bio/BlastHTTP.o )

src/Bio/BlastHTTP.hs:89:5: error:
    Variable not in scope:
      withManager
        :: (Manager -> m0 (Network.HTTP.Conduit.Response L8.ByteString))
           -> IO (Network.HTTP.Conduit.Response L8.ByteString)
   |
89 |     withManager $ httpLbs req
   |     ^^^^^^^^^^^
```

I was able to reproduce the error locally like so:

```bash
stack unpack BlastHTTP-1.2.1 && cd BlastHTTP-1.2.1
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- http-conduit-2.3.0
```
